defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
  
# Site settings
title: Paul Kuttiya
email: w.kuttiya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Paul Kuttiya portfollio website
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
img_path: "https://s3.us-east-2.amazonaws.com/pkuttiya-site/img"
linkedin: 
github: https://github.com/pookzzz2231

# Build settings
livereload: true
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-haml
  - github-pages"
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
